# import so you can load in safetensors

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from safetensors.torch import load_file

from rsp.constants import *

pre_path = f"{RESULTS_DIR}/anycost"
p = "/google-ddpm-ema-celebahq-256steps100-"
pth = "hspace-after-etasNone-idxsize10000.safetensors"

data = load_file(f"{pre_path}{p}{pth}", device="cpu")
attr = data["attr"]
attr = attr[attr[:, 0] != -1]  # filter out invalid entries

# make a correlation matrix of all aus
aus = SUPPORTED_AUS
df = pd.DataFrame(attr.numpy(), columns=aus)
correlation_matrix = df.corr()
# save figure
plt.figure(figsize=(12, 10))
sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    vmin=-1,
    vmax=1,
)
plt.xlabel("Action Unit", fontsize=20)
plt.title("AU Correlation Matrix Generated Images", fontsize=20)
plt.ylabel("Action Unit", fontsize=20)
plt.tight_layout()
# increase tick size (so the one with the actual AU's
plt.xticks(fontsize=20)
plt.tick_params(axis="y", rotation=0, labelsize=20)

plt.savefig("au_correlation_matrix.png", bbox_inches="tight")
plt.close()


# Data file is not pushed in repo due to size
# but the file is generated by running the pyfeat_save_first.py script
# on the original celebA-HQ dataset and saving the results to csv

path = "../rsp/data/results100k.csv"
df_real = pd.read_csv(path)
df_real = df_real[aus]


correlation_matrix_real = df_real.corr()
plt.figure(figsize=(12, 10))
sns.heatmap(
    correlation_matrix_real,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    vmin=-1,
    vmax=1,
)
plt.title("AU Correlation Matrix - Real Data", fontsize=20)
plt.xlabel("Action Unit", fontsize=20)
plt.ylabel("Action Unit", fontsize=20)
plt.xticks(fontsize=20)
# and flip y ticks 90 degrees
plt.tick_params(axis="y", rotation=0, labelsize=20)

plt.tight_layout()
plt.savefig("au_correlation_matrix_real.png", bbox_inches="tight")
plt.close()
