"""Constants used throughout the project."""

from pathlib import Path

BASE_DIR = Path(__file__).parent.parent.parent

RESULTS_DIR = BASE_DIR / "results"
if not RESULTS_DIR.exists():
    RESULTS_DIR.mkdir()

AU_TO_FACS_MAP = {
    "AU01": "Inner Brow Raiser",
    "AU02": "Outer Brow Raiser",
    "AU03": "Inner corner Brow Tightener",
    "AU04": "Brow Lowerer",
    "AU05": "Upper Lid Raiser",
    "AU06": "Cheek Raiser",
    "AU07": "Lid Tightener",
    "AU08": "Lips Toward Each Other",
    "AU09": "Nose Wrinkler",
    "AU10": "Upper Lip Raiser",
    "AU11": "Nasolabial Deepener",
    "AU12": "Lip Corner Puller",
    "AU13": "Sharp Lip Puller",
    "AU14": "Dimpler",
    "AU15": "Lip Corner Depressor",
    "AU16": "Lower Lip Depressor",
    "AU17": "Chin Raiser",
    "AU18": "Lip Pucker",
    "AU19": "Tongue Show",
    "AU20": "Lip Stretcher",
    "AU21": "Neck Tightener",
    "AU22": "Lip Funneler",
    "AU23": "Lip Tightener",
    "AU24": "Lip Pressor",
    "AU25": "Lip Part",
    "AU26": "Jaw Drop",
    "AU27": "Mouth Stretch",
    "AU28": "Lip Suck",
    "AU29": "Jaw Thrust",
    "AU30": "Jaw Sideways",
    "AU31": "Jaw Clencher",
    "AU32": "Lip Bite",
    "AU33": "Cheek Blow",
    "AU34": "Cheek Puff",
    "AU35": "Cheek Suck",
    "AU37": "Lip Wipe",
    "AU38": "Nostril Dilator",
    "AU39": "Nostril Compressor",
    "AU40": "Sniff",
    "AU41": "Lid Drop",
    "AU42": "Slit",
    "AU43": "Eyes Closed",
    "AU44": "Squint",
    "AU45": "Blink",
    "AU46": "Wink",
    "AU51": "Head turn left",
    "AU52": "Head turn right",
    "AU53": "Head up",
    "AU54": "Head down",
    "AU55": "Head tilt left",
    "AU56": "Head tilt right",
    "AU57": "Head forward",
    "AU58": "Head backward",
    "AU61": "Eyes turn left",
    "AU62": "Eyes turn right",
    "AU63": "Eyes up",
    "AU64": "Eyes down",
    "AU65": "Strabismus",
    "AU66": "Cross-eyed",
}

AU_TO_EMOTION_MAP = {
    "AU1": ["sadness", "surprise", "fear"],
    "AU2": ["surprise", "fear"],
    "AU4": ["sadness", "fear", "anger"],
    "AU5": ["surprise", "fear", "anger"],
    "AU6": ["happiness", "disgust", "contempt"],
    "AU7": ["fear", "anger"],
    "AU8": ["none"],
    "AU9": ["disgust"],
    "AU11": ["disgust", "fear"],
    "AU12": ["happiness", "contempt"],
    "AU14": ["contempt"],
    "AU15": ["sadness", "disgust"],
    "AU17": ["disgust"],
    "AU20": ["fear"],
    "AU23": ["anger"],
    "AU25": ["happiness", "surprise", "fear"],
    "AU26": ["fear", "surprise"],
    "AU38": ["anger"],
}

SUPPORTED_AUS = [
    "AU01",
    "AU02",
    "AU04",
    "AU05",
    "AU06",
    "AU07",
    "AU09",
    "AU10",
    "AU11",
    "AU12",
    "AU14",
    "AU15",
    "AU17",
    "AU20",
    "AU23",
    "AU24",
    "AU25",
    "AU26",
    "AU28",
    "AU43",
]

AU_SUBSET = [
    "AU04",
    "AU06",
    "AU10",
    "AU12",
]
